name: lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: false
      - name: Go linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: --timeout=30m
          install-mode: binary
