name: test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - README.md
      - "releases/**"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: go test -race -count 1 ./...

      - name: Coverage Test
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'master' }}
        run: go test -count 1 -coverprofile=coverage.txt ./...

      - name: Upload Coverage
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'master' }}
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: grafana/k6pack

      - name: Generate Go Report Card
        if: ${{ matrix.platform == 'ubuntu-latest' && github.ref_name == 'master' }}
        uses: creekorful/goreportcard-action@v1.0
